#!/bin/bash

set -x
exec 2>/tmp/err-$$.txt

# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# DELETE <host:remote_system_ds/disk.i|host:remote_system_ds/>
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host

DST=$1
VM_ID=$2
DS_ID=$3

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------
SRC_PATH=`arg_path $SRC`
SRC_HOST=`arg_host $SRC`

DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`


#-------------------------------------------------------------------------------
# getting detailed volume informations
#-------------------------------------------------------------------------------

if [ `is_disk $DST_PATH` -eq 1 ]; then

	DRIVER_PATH=$(dirname $0)

	DISK_ID=$(echo "$DST_PATH" | $AWK -F. '{print $NF}')

	XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

	unset i XPATH_ELEMENTS

	#
	# parse vm volume details from "onevm" xml output
	#

	while IFS= read -r -d '' element; do
	    XPATH_ELEMENTS[i++]="$element"
	done < <(onevm show -x $VM_ID| $XPATH \
			    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/PERSISTENT)

	PERSISTENT="${XPATH_ELEMENTS[0]}"

#-------------------------------------------------------------------------------

# Delete the device if it's a clone (LVM snapshot)
DELETE_CMD=$(cat <<EOF
    exec 2>/tmp/err-$$.txt
    set -x
    echo \$0
    DEV=\$(readlink $DST_PATH)
    LV=\$(basename \$DEV)

    # we remove volume only if lv is snapshot - named "lv-one-{PARENTVOLID}-{VMID}-{DISKID}"
    VM=\$(echo \$LV|cut -d- -f4)
    DISK_ID=\$(echo \$LV|cut -d- -f5)
    #if [ -n "\$VM" -a -n "\$DISK_ID" ]; then

        # persistent volume should not be removed
        if [ "$PERSISTENT" != "YES" ]
        then
            $SUDO $LVREMOVE -f \$DEV
        fi
    #fi
EOF
)

    # Disk
    ssh_exec_and_log "$DST_HOST" "$DELETE_CMD" \
        "Error deleting $DST_PATH"
else
    # Directory
    log "Deleting $DST_PATH"
    ssh_exec_and_log "$DST_HOST" "rm -rf $DST_PATH" "Error deleting $DST_PATH"
fi

exit 0
