#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2013, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

source $(dirname $0)/kvmrc
source $(dirname $0)/../../scripts_common.sh

domain=$1

mkdir -p `dirname $domain`
cat > $domain

# be safe and keep older acpabilities for migration betwen upgraded
# and not yet upgdared hypervizor servers
sed -i -e "s|<type arch='x86_64'>hvm</type>|<type arch='x86_64' machine='rhel6.2.0'>hvm</type>|" $domain

# set cgroups cpu shares to number of vcups
# to be more restrict cpu usage
if grep -q cputune $domain
then
	:
else
	vcpu="$(grep '<vcpu>' $domain | cut -d '>' -f 2 | cut -d '<' -f 1 )"
	shares="$((1024*$vcpu))"
	sed -ie 's,</domain>,<cputune><shares>'"$shares"'</shares></cputune></domain>,' $domain
fi

data=`virsh --connect $LIBVIRT_URI create $domain`

if [ "x$?" = "x0" ]; then
    echo $data | sed 's/Domain //' | sed 's/ created from .*$//'
else
    error_message "Could not create domain from $domain"
    exit -1
fi
